### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by andlaus**
this PR contains a few minor improvements, mostly to get rid of compiler warnings that appear with elated warning levels (`-Wextra`). I could not test this on the current master because the build fails for me (probably due to some specifics of my local setup), but hopefully Jenkins gets through.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this with downstreams please

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
jenkins is happy. Since this is not a "high risk" PR, I'll merge this tomorrow if there are no objections.

**Comment by atgeirr** [comment]
> jenkins is happy. Since this is not a "high risk" PR, I'll merge this tomorrow if there are no objections.

No objections. Assuming this is a not-changing-a-bit-of-the-solutions (NCABOTS) PR?

**Comment by andlaus** [comment]
> Assuming this is a not-changing-a-bit-of-the-solutions (NCABOTS) PR?

in principle this should be the case, but c++ compilers surprised me too often already: e.g. it could be that removing an unneeded function (the third patch) changes the results. anyway, I'll merge now, thanks for looking at this.

**Pull request merged**
