### PR TITLE
Some changes to facilitate building using a super project 

### PR DESCRIPTION
**Pull request by akva2**
See https://github.com/OPM/opm-common/pull/321

### CODE REVIEW

**Comment by andlaus** [comment]
no real objections, merge whenever.

a thing which strikes me as a bit ugly is that the "DEPENDS ewoms_prepare" must be added to all invocations of `opm_add_test()`. possibly it is better to modify the opm_add_test() macro, but there might be difficulties with this that I do not see?

**Comment by akva2** [comment]
i could modify the macro to read a global variable, if you prefer. i just used existing facilities.

**Comment by andlaus** [comment]
both are fine with me, so pick the one which you prefer. isn't there a "PROJECT_NAME" variable so that  opm_add_test() macro could make tests automatically depend on the "${PROJECT_NAME}_prepare" target if it exists?

**Comment by akva2** [comment]
hmm, i like that idea.

**Pull request merged**
