### PR TITLE
remove ebos from packaging

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by andlaus** [comment]
thanks. possibly, it should be added to the opm-simulators package as well. probably not -- the target audience is supposed to compile it themselves anyway...

**Comment by akva2** [comment]
opm-simulators already package all installed applications so nothing has to be done.

**Comment by andlaus** [comment]
will the `ebos` binary be included in it automatically?

**Comment by andlaus** [comment]
forget my last comment, I slightly misread yours. Sorry.

**Pull request merged**
