### PR TITLE
changed to have pressure as first variable for 3ph blackoil

### PR DESCRIPTION
**Pull request by hnil**
Move pressure to be first variable.
This together with setting water equation as first equation make some implementations of cpr simpler. 
The pullrequest also adds the spessializations need for using our matrixes with matrix market.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this opm-material=324

**Comment by andlaus** [comment]
I'm not sure if this is a good idea, see my comment for OPM/opm-material#324.

**Comment by andlaus** [comment]
(also, jenkins is currently unhappy)

**Comment by andlaus** [comment]
With the CPR stuff merged to opm-simulators, I'm pretty sure that this is obsolete. Closing tentatively.

**Pull request closed without merging**
