### PR TITLE
Pass enableSwatinit to the OPM initialization 

### PR DESCRIPTION
**Pull request by totto82**
Only apply swatinit in the initialization if swatinit is enabled.

### CODE REVIEW

**Comment by andlaus** [comment]
are you sure that this is correct? SWATINIT does not get applied to the material law manager here but only later in the problem (via `EclProblem::applySwatinit()`). That said I'm not very familiar with `Opm::initStateEquil()`...

**Comment by andlaus** [comment]
as far as I can tell, the PR is good to go in from the code point of view. please merge it yourself once you convinced yourself that it is semantically correct. (thank for the work, BTW!)

**Comment by totto82** [comment]
> are you sure that this is correct?

If enableSwatinit is set to false it will be ignored also in the computation of the threshold pressures. 
When calling flow_ebos the order of calculations is as follows
1) the initial state is calculated in ebos without SWATINIT (since enableSwatinit==false) 
2) default th-press is calculated
3) the initial state is calculated in flowEbosMain.hpp with SWATINIT. The call to Opm::initStateEquil() will also apply swatinit to the material law manager.

**Comment by totto82** [comment]
I think the logic is "correct", at least in the sense that it reproduces Ecl.  I still think it is more sensible to include the SWATINIT effects in the default th-pressure calculations. (i.e. revert this PR). 

I also made some small changes to the thpressure calculations (excluding faces with negligible flow). I am still waiting for the full simulation to complete.

**Comment by andlaus** [comment]
> I think the logic is "correct", at least in the sense that it reproduces Ecl.

ok, I see. go ahead and merge it. please make travis happy before, though.

**Comment by atgeirr** [comment]
> I still think it is more sensible to include the SWATINIT effects in the default th-pressure calculations.

So should we wait for that solution to be implemented, or aim towards merging this?

**Comment by atgeirr** [comment]
jenkins build this opm-core=1129 please

**Comment by totto82** [comment]
> That solution

 is the current solution. So no need for waiting. But we should keep this issue in mind if (or when) we rewrite the initialization code.

**Pull request merged**
