### PR TITLE
Rockcomp

### PR DESCRIPTION
**Pull request by totto82**
This is a refreshed version of #491. Thanks to @andlaus

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by totto82** [comment]
This includes #501 and therefore depends on the opm-material PR.

**Comment by andlaus** [comment]
okay. I suppose we should wait to merge this until the 2019.04 release is out of the door anyway...

**Comment by totto82** [comment]
jenkins build this please

**Comment by andlaus** [comment]
weird: the SoMax Scalar->Evaluation change seems to be still here. I thought this was already dealt with by #501. maybe you should rebase this, @totto82?

**Comment by totto82** [comment]
I have started Jenkins from the opm-simulator side. I think should go in know when/if Jenkins is happy

**Comment by andlaus** [comment]
I agree. be aware that Jenkins seemed to have trouble with connecting to github about an hour ago, so maybe this takes a few attempts...

**Comment by andlaus** [comment]
seems like the jenkins issues are gone. Since this PR is tiny and seems to be self-contained, I'll merge it now...

**Pull request merged**
