### PR TITLE
Fix dune master

### PR DESCRIPTION
**Pull request by andlaus**
This fixes the build on the latest master version of Dune  (i.e., what is most likely to become Dune 2.7). Probably this needs to be revised when Dune 2.7 gets released, but the changes are beneficial on their own and they're also not very complicated.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=291 please

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=291 please

**Comment by andlaus** [comment]
*arg* jenkins used the old version of the opm-material branch again. next try!

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=291 please

**Comment by andlaus** [comment]
jenkins or github still screw up because it uses revision d4897273 for opm-material while OPM/opm-material#291 is actually at b0f2e975. Since the issue is fixed on my machine locally, I'll merge it despite the jenkins complaint.

@akva2 any ideas of how to get around this issue?

**Comment by akva2** [comment]
only patience. it's github lag, not much can be done about it unfortunately.

**Pull request merged**
