### PR TITLE
ebos: remove the code to calculate a mass conservative initial condtion if the specified condition is inconsistent

### PR DESCRIPTION
**Pull request by andlaus**
As far as I can see, this was always set to `false` anyway.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by totto82** [comment]
Why is the mpi.powerinjection_forchheimer_fd affected by this PR?

**Comment by andlaus** [comment]
it should not be because this is PR at the other end of the spectrum of code used by this test. the error seems to be unrelated and somewhere in libc. maybe there's a rarely triggered race condition somewhere. let's try again.

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
yay! it worked! no changes whatsoever!

**Comment by totto82** [comment]
Thanks. Jenkins ways are sometimes mysterious.

**Pull request merged**
