### PR TITLE
Remove ArtGridManager.

### PR DESCRIPTION
**Pull request by dr-robertk**
The functionality of ArtGridManager has been outsourced to art2dgf.cc and the DgfGridManager is now capable of reading fractures (as before only 2d). 

The fracture_discretefracture test passes (with the sfc disabled that will be investigated).

### CODE REVIEW

**Comment by dr-robertk** [comment]
patch applied.

**Comment by dr-robertk** [comment]
I have added the possibility to also handle fractures in 3d (for the sake of completeness). This PR is good to go from my side.

**Comment by andlaus** [comment]
I'm eager to merge this, but the test of the discrete fracture model still fails for some weird reason:

```
> ctest -R fracture_discretefracture -V
[...]
39: Allocating the grid
39: 
39: Created serial ALUGrid<2,2,simplex,nonconforming> from macro grid file 'data/fracture.art.dgf.
39: 
39: fracture_discretefracture: /home/and/src/dune-grid/dune/grid/common/mcmgmapper.hh:193: Index Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLevelGridViewTraits<const Dune::ALUGrid<2, 2, 0, 1, Dune::ALUGridMPIComm>, 4> >, Dune::MCMGElementLayout>::subIndex(const typename GV::template GV::Codim<0>::Entity &, int, unsigned int) const [GV = Dune::GridView<Dune::DefaultLevelGridViewTraits<const Dune::ALUGrid<2, 2, 0, 1, Dune::ALUGridMPIComm>, 4> >, Layout = Dune::MCMGElementLayout]: Assertion `layout.contains(gt)' failed.
39: Executing the binary failed!
1/1 Test #39: fracture_discretefracture ........***Failed    0.20 sec
```

this happens on both, the latest master and paramerge branches of dune-alugrid (with dune 2.4). any ideas?

**Comment by dr-robertk** [comment]
I get 

1/1 Test #39: fracture_discretefracture ........   Passed    1.87 sec

The following tests passed:
        fracture_discretefracture

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   1.95 sec

**Comment by dr-robertk** [comment]
I'm using dune 2.4 and alugrid paramerge the latest.

**Comment by dr-robertk** [comment]
I'll double check.

**Comment by dr-robertk** [comment]
Should be fixed now. The layout for the mapper was wrong.

**Comment by andlaus** [comment]
thanks. now it works for me, too. (I suppose that you disabled assertations?) merging.

**Comment by dr-robertk** [comment]
Yep, assertions were disabled.

**Pull request merged**
