### PR TITLE
Using new EclipseState API

### PR DESCRIPTION
**Pull request by pgdr**
Downstream: 
- OPM/opm-parser#751
- OPM/opm-material#137
- OPM/opm-core#994
- OPM/opm-simulators#644
- OPM/opm-output#14

### CODE REVIEW

**Comment by pgdr** [comment]
jenkins build this opm-parser=751 opm-material=137 opm-output=14 opm-core=994 opm-simulators#644 please

**Comment by jokva** [comment]
@andlaus This passes. We're good to go? (upstream has been merged).

**Comment by andlaus** [comment]
Ok: I tested it and there was a minor build problem for which I opened a PR on top of your personal fork's branch (i.e., press green there and it will be in this PR): https://github.com/pgdr/ewoms/pull/1

everything else which I've tested (SPE-1 and SPE-9) seems to work fine. Thanks for the work.

**Comment by andlaus** [comment]
> @andlaus This passes. We're good to go? (upstream has been merged).

yeah, I'd prefer to wait until @pgdr pressed green on the amendment PR, but if that takes too long I'll merge in the afternoon and fix up the build...

**Comment by jokva** [comment]
In the green.

**Comment by andlaus** [comment]
good, thanks!

**Pull request merged**
