### PR TITLE
WIP: Remove strict-parsing option

### PR DESCRIPTION
**Pull request by joakim-hove**
Seems this should be in flow/opm-simulators: https://github.com/OPM/opm-simulators/pull/1704

### CODE REVIEW

**Comment by andlaus** [comment]
well, the parameter is still there. you can also access it in the `flow` context...

**Comment by joakim-hove** [comment]
> well, the parameter is still there. you can also access it in the flow context...

OK - whatever; I don't really understand this. Wheh I combined `ewoms:master` with https://github.com/OPM/opm-simulators/pull/1704 I got the message:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  Parameter EclStrictParsing registered twice with non-matching characteristics.
Aborted (core dumped)
```
so I concluded that it should only be in `flow` - but I appreciate guidance on this.

**Comment by andlaus** [comment]
yes, must then remove the `EWOMS_REGISTER_PARAM()` call for `EclStrictParsing` from opm-simulators.

**Comment by joakim-hove** [comment]
> yes, must then remove the EWOMS_REGISTER_PARAM() call for EclStrictParsing from opm-simulators.

OK - but will it then be accessable from opm-simulators; specifically before the parsing has started?

**Comment by andlaus** [comment]
(registering the same parameter twice with different descriptions or types would lead to inconsistencies.)

**Comment by andlaus** [comment]
> OK - but will it then be accessable from opm-simulators; specifically before the parsing has started?

I think so.

**Comment by andlaus** [comment]
actually, I'm willing to bet a beer on this because the file name of the deck to be parsed is determined via the parameter system.

**Comment by joakim-hove** [comment]
> I think so.

I hope you are right - but I think you are wrong.

> I'm willing to bet a beer on this because the file name of the deck to be parsed is determined via the parameter system.

Yes - but that is some uber-hack to avoid a Catch22 - I tried to hook into the same hack, but ....

**Comment by joakim-hove** [comment]
I give up for now - will pick it up again. I have really tried, but getting the parameter system to adhere to my whims is not exactly walk in the park.

What I want to achieve is that `flow` supports an option - like `--ecl-strict-parsing`[1] and that I can get access to that `bool` setting [here](https://github.com/OPM/opm-simulators/pull/1704/files#diff-fa1067ba914130bd73d02fe3a49a4ad0R186) - might be walk in the park for you?

[1]: Preferably without having to add a `=true` - but that is not essential.

**Comment by andlaus** [comment]
I suppose that programming a reservoir simulator is not for the faint of heart. merge joakim-hove/opm-simulators#3 and you are golden (be aware that is a PR for your opm-simulators PR).

**Pull request closed without merging**
