### PR TITLE
Add support for miscible solvent runs

### PR DESCRIPTION
**Pull request by totto82**
- initialization only via Ecl Deck
- adds modification of relperms and cap-pressures for miscible runs
- adds TL mixing model for effective viscosity and density calculations

Tested on SPE1CASE2_SOLVENT_MISC_TL, SPE9_CP_CO2_MISC_TL, SPE5CASE1-3
and SPE3CASE1_SOLVENT_MISC

Issues:
- some discrepancy of the results for the SPE3 case compared to
flow_solvent.
- some extra convergence issues on the SPE5s and SPE9.

Issues most probably related to the well handling.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this with downstreams please

**Comment by andlaus** [comment]
nice! I've skimmed over the patch and nothing obviously wrong hit me. are you aware of any issues which need to be fixed before merging or do you think it is ready?

**Comment by totto82** [comment]
I have a few more minor fixes I want to include before it is ready. 
Any idea why Jenkins is unhappy?

**Comment by totto82** [comment]
Now all the issues reported in the PR is fixed. If Jenkins is happy this can be merged.

**Comment by andlaus** [comment]
> Any idea why Jenkins is unhappy?

the `compareECLInitFiles_flow_ebos+NORNE_ATW2013` test from opm-simulators fails. probably not because this PR, though?

**Comment by andlaus** [comment]
hm, that issue also occurs locally on my machine:

```
32: Program threw an exception: [/home/and/src/opm-output/opm/test_util/EclFilesComparator.cpp:370] Deviations exceed tolerances.
32: The absolute deviation is 0.0301113, and the tolerance limit is 0.02.
32: The relative deviation is 0.00106973, and the tolerance limit is 1e-05.
32: Comparing '/home/and/src/opm-simulators/tests/results/init/flow_ebos+norne/NORNE_ATW2013' to '/home/and/src/opm-simulators/../opm-data/norne/opm-simulation-reference/flow_ebos/NORNE_ATW2013'.
```

could #184 be the culprit?

**Comment by andlaus** [comment]
ok, seems like #184 *was* the culprit. fixed by #186.

**Comment by totto82** [comment]
The #184 may change TRANX. I noticed Jenkins was never asked for #184. Maybe reverting #184, making a new PR and then ask Jenkins?

**Comment by totto82** [comment]
I guess you already did the reverting part in #186. We need the fix in #184. Should I make a new PR?

**Comment by andlaus** [comment]
I hope that the fix for the negative cartesian indices is still present in #186 because cartesian indices should not be used outside of the cell volume accumulation while loop anymore.

**Comment by andlaus** [comment]
jenkins build this with downstreams please

**Comment by andlaus** [comment]
jenkins is happy at last. merging!

**Pull request merged**
