### PR TITLE
Equil initialization with ALUGrid and parallel ecl output.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR fixes the EQUIL initialization for ALUGrid.
It also adds parallel output to EclWriter. This also fixes the previously existing problem when elements were reordered using an SFC approach. 

This was tested with SPE9_CP.DATA

### CODE REVIEW

**Comment by dr-robertk** [comment]
This PR is superseded by #37.

**Comment by andlaus** [comment]
it seems like you forgot to `git add ewoms/parallel/collecttoiorank.hh`?

**Comment by dr-robertk** [comment]
Fixed.

**Comment by andlaus** [comment]
thanks. now I get

```
In file included from /home/and/src/ewoms/applications/ebos/ebos.cc:31:
In file included from /home/and/src/ewoms/applications/ebos/eclproblem.hh:31:
In file included from /home/and/src/ewoms/applications/ebos/eclgridmanager.hh:34:
In file included from /home/and/src/dune-cornerpoint/dune/grid/polyhedralgrid.hh:1:
/home/and/src/dune-cornerpoint/dune/grid/polyhedralgrid/grid.hh:326:7: error: call to constructor of 'std::unique_ptr<UnstructuredGridType, UnstructuredGridDeleter>' is ambiguous
    : gridPtr_( 0 ),
      ^         ~
/home/and/src/ewoms/applications/ebos/eclgridmanager.hh:375:48: note: in instantiation of member function 'Dune::PolyhedralGrid<3, 3>::PolyhedralGrid' requested here
            equilgrid_ = EquilGridPointer( new EquilGrid( *ug ) );
                                               ^
/home/and/src/ewoms/applications/ebos/eclgridmanager.hh:353:13: note: in instantiation of member function 'Ewoms::EclGridManager<Ewoms::Properties::TTag::EclProblem>::createEquilGrid' requested here
            createEquilGrid();
            ^
/home/and/src/ewoms/applications/ebos/eclequilinitializer.hh:79:47: note: in instantiation of member function 'Ewoms::EclGridManager<Ewoms::Properties::TTag::EclProblem>::equilGrid' requested here
        const auto& equilGrid   = gridManager.equilGrid();
                                              ^
/home/and/src/ewoms/applications/ebos/eclproblem.hh:856:26: note: in instantiation of function template specialization
      'Ewoms::EclEquilInitializer<Ewoms::Properties::TTag::EclProblem>::EclEquilInitializer<Opm::EclMaterialLawManager<Opm::ThreePhaseMaterialTraits<double, 0, 1, 2> > >' requested here
        EquilInitializer equilInitializer(this->simulator(), materialLawManager_);
                         ^
/home/and/src/ewoms/applications/ebos/eclproblem.hh:848:13: note: in instantiation of member function 'Ewoms::EclProblem<Ewoms::Properties::TTag::EclProblem>::readEquilInitialCondition_' requested here
            readEquilInitialCondition_();
            ^
/home/and/src/ewoms/applications/ebos/eclproblem.hh:278:9: note: in instantiation of member function 'Ewoms::EclProblem<Ewoms::Properties::TTag::EclProblem>::readInitialCondition_' requested here
        readInitialCondition_();
        ^
/home/and/src/ewoms/ewoms/common/simulator.hh:126:19: note: in instantiation of member function 'Ewoms::EclProblem<Ewoms::Properties::TTag::EclProblem>::finishInit' requested here
        problem_->finishInit();
                  ^
/home/and/src/ewoms/ewoms/common/start.hh:291:19: note: in instantiation of member function 'Ewoms::Simulator<Ewoms::Properties::TTag::EclProblem>::Simulator' requested here
        Simulator simulator;
                  ^
/home/and/src/ewoms/applications/ebos/ebos.cc:41:19: note: in instantiation of function template specialization 'Ewoms::start<Ewoms::Properties::TTag::EclProblem>' requested here
    return Ewoms::start<ProblemTypeTag>(argc, argv);
                  ^
/usr/bin/../lib64/gcc/x86_64-suse-linux/4.9/../../../../include/c++/4.9/bits/unique_ptr.h:169:7: note: candidate constructor
      unique_ptr(pointer __p) noexcept
      ^
/usr/bin/../lib64/gcc/x86_64-suse-linux/4.9/../../../../include/c++/4.9/bits/unique_ptr.h:200:17: note: candidate constructor
      constexpr unique_ptr(nullptr_t) noexcept : unique_ptr() { }
                ^
/usr/bin/../lib64/gcc/x86_64-suse-linux/4.9/../../../../include/c++/4.9/bits/unique_ptr.h:205:7: note: candidate constructor
      unique_ptr(unique_ptr&& __u) noexcept
      ^
/usr/bin/../lib64/gcc/x86_64-suse-linux/4.9/../../../../include/c++/4.9/bits/unique_ptr.h:356:7: note: candidate constructor has been explicitly deleted
      unique_ptr(const unique_ptr&) = delete;
```

**Comment by dr-robertk** [comment]
You need to update dune-cornerpoint.

**Comment by andlaus** [comment]
ah. sorry.

**Comment by andlaus** [comment]
alright, it now compiles and all tests which passed before still pass. merging & thank you!

**Pull request merged**
