### PR TITLE
Fix clang warnings

### PR DESCRIPTION
**Pull request by andlaus**
this fixes a few clang-only warnings on master and works around an dune-grid (or opm-grid?) issue with newer clang versions.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this with downstreams please

**Comment by andlaus** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
Do you know what is happening to the GeometryType in Dune 2.6?

**Comment by andlaus** [comment]
not really. it seems they want to replace it by a "topologyId" which is a totally opaque integer (at least to me). Progress, I guess...

**Comment by andlaus** [comment]
with jenkins happy and the changes being  minor, let's merge.

**Pull request merged**
