### PR TITLE
first attempt to fixing the Evaluation with value 1.0

### PR DESCRIPTION
**Pull request by GitPaean**
@andlaus , how do you think?

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by andlaus** [comment]
I see what you mean, this is not exactly pretty. how about handling `DynamicEvaluations` with zero derivatives as constants. This would require a few case distinctions, but would allow to instantiate `DynamicEvaluation`s that represent  constants without having to specify a size...

**Comment by atgeirr** [comment]
> I see what you mean, this is not exactly pretty. how about treating `DynamicEvaluations` with zero derivatives as constants? This would require a few case distinctions, but would allow to instantiate `DynamicEvaluation`s that represent constants without having to specify a size...

I suggested this a while ago, and still think it is a good idea, so I support that!

**Comment by GitPaean** [comment]
> DynamicEvaluations with zero derivatives as constants? 

Sorry I did not see your comment yesterday.  Then we will support a constructor that can create a DynamicEvaluation from a Scalar value, then it is possible we will recover some old grammar before introduced DynamicEvaluation.  The DynamicEvalution makes us have to specify the number of the primary variables at its current form.

**Comment by andlaus** [comment]
this has become obsolete with #517. closing.

**Pull request closed without merging**
