### PR TITLE
EclEquilInitializer: make it work for ALUGrid.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR fixes the EQUIL initialization for ALUGrid. However, there seems to be a problem with space filling curve ordering. That is either an ALUGrid problem or a problem of initStateEquil.

This was tested with SPE9_CP.DATA

### CODE REVIEW

**Comment by dr-robertk** [comment]
I just checked, the problem is the reordering of cells which destroys the one to one relation between the CpGrid and ALUGrid. I will fix this in a little bit. For now it works as is.

**Comment by andlaus** [comment]
I'm currently working on a more generic (albeit less efficient) solution which also works for parallel runs and arbitrary cell ordering. I hope to get this into a working condition soon.

**Comment by dr-robertk** [comment]
I have pushed an update that includes the general initialization of PolyhedralGrid given a DUNE grid.
Please take a look. It works but the Eclwriter does not yet respect the cell reordering.

**Comment by dr-robertk** [comment]
This PR is superseded by #37.

**Pull request closed without merging**
