### PR TITLE
parameter system: allow to specify empty strings

### PR DESCRIPTION
**Pull request by andlaus**
this might be wanted in some instances.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks. This will allow for output-dir="" i.e to make the output directory the same as the input one.

**Comment by atgeirr** [comment]
> This will allow for output-dir=""

Will it? Or will it just allow for `--output-dir=` with no quotes? I have nothing against this, just curious.

**Comment by andlaus** [comment]
> Will it? Or will it just allow for --output-dir= with no quotes? I have nothing against this, just curious.

both: the quotes are "eaten" by the shell...

**Pull request merged**
