### PR TITLE
Add support for PBDV and PDDV in initstateequil.hh

### PR DESCRIPTION
**Pull request by totto82**
Depends on OPM/opm-parser#1182

### CODE REVIEW

**Comment by andlaus** [comment]
from the core eWoms angle, this looks good. so permission to merge at convenience granted.

I cannot say too much about the actual code changes, though. any opinions @bska or @atgeirr?

**Comment by atgeirr** [comment]
> I cannot say too much about the actual code changes, though. any opinions @bska or @atgeirr?

@bska will review and test this for correctness

**Comment by bska** [comment]
> will review and test this for correctness

Initial glance looks good, but I don't understand why you use constant extrapolation for PBVD and linear extrapolation for PDVD.  I would have thought that you'd need to treat those descriptions the same way.

**Comment by totto82** [comment]
> Initial glance looks good, but I don't understand why you use constant extrapolation for PBVD and linear extrapolation for PDVD. I would have thought that you'd need to treat those descriptions the same way.

It based on testing against "the reference simulator", and I agree it is strange. One solution I haven't tested is to use linear extrapolation in one end and constant extrapolation in the other end. I can setup a few more tests to  check this out.

**Comment by bska** [comment]
> I can setup a few more tests to check this out.

If it's not too much trouble, then yes I think that'd be a worthwhile endeavour.

**Comment by totto82** [comment]
> If it's not too much trouble, then yes I think that'd be a worthwhile endeavour.

It was worth it as it reveled a bug. The pressure in the endpoints of the table should be restricted by the cell pressure.

**Comment by bska** [comment]
> The pressure in the endpoints of the table should be restricted by the cell pressure.

Ah, right.  One final nit and then this can be installed.  The documentation for PDVD should refer to "RV" rather than "RS" when describing the input parameters to the function call operator.  Other than that I'm satisfied with the state of this.

**Comment by totto82** [comment]
@bska Thanks for the review.

**Comment by atgeirr** [comment]
I'll start a test, we'll merge when green.

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by andlaus** [comment]
@totto82: do you consider this ready to be merged?

**Comment by totto82** [comment]
Yes, it is ready when Jenkins is ready.

**Comment by atgeirr** [comment]
Then in it goes! Thanks for the patch, and for the review.

**Pull request merged**
