### PR TITLE
Some property- and parameter system improvements

### PR DESCRIPTION
**Pull request by andlaus**
The parameter system retrieves more changes: This PR adds support for positional command line parameters and overhauls the system how the help messages are created. As a guiney pig, ebos gets support for positional parameters, and a description of is added to the help messages of ebos and the lens_* simulators.

the property system only introduces `BEGIN_PROPERTIES` and `END_PROPERTIES` macros in order to be flexible on how properties are declared in the future. Note that while this is not a very significant change in itself, converting all code to use these macros implies plenty of boiler plate changes, i.e., it is best to review the individual patches of this PR instead of the accumulated changes. (if wanted, it can also be split because it is fully bisectable.)

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
yes, but is trival enough not to warrant a separate PR?! (it does not contain any functional changes)

the usual procedure for such micro-cleanups so far has been to embedd in other PRs so far, usually not even in a separate patch. If you want to change this, I'll open a separate PR and point such stuff out in my reviews, too.

**Comment by andlaus** [comment]
jenkins build this please

**Comment by totto82** [comment]
Looks fine. I will merge it when the test is done.

**Pull request merged**
