### PR TITLE
Add transpose to MatrixBlock.

### PR DESCRIPTION
**Pull request by atgeirr**
This is needed for the CPR work.

### CODE REVIEW

**Comment by andlaus** [comment]
I'm not sure if doing it like this is a terribly good idea: it will prevent using `Dune::FieldMatrix` for code which uses this. Making this a free function (e.g., `Ewoms::transposeMatrix(M)`), would be a better approach as far as I can see.

**Comment by andlaus** [comment]
or -- even better -- move this free function to the CPR code in opm-simulators.

**Comment by atgeirr** [comment]
> it will prevent using `Dune::FieldMatrix` for code which uses this.

I think the problem is the opposite: Dune::FieldMatrix.transpose() is defined and used, but fails for MatrixBlock. (@hnil please correct me if I misunderstood this.)

**Comment by blattms** [comment]
It might fail because the code might not see FieldMatrix but only
DenseMatrix (which does not have the transpose function)

**Comment by andlaus** [comment]
I'm not sure which version of DUNE you use, but for Dune 2.6, the following snippet does not compile on my machine:

```c++
#include <dune/common/fmatrix.hh>

int main(int argc, char **argv)
{
    Dune::FieldMatrix<double, 2, 2> foo;
    foo.transpose();
    return 0;
}
```

**Comment by blattms** [comment]
I did not check and just believed somebody claiming it existed. Indeed it does not exist and I was talking about an imaginary version.

**Comment by andlaus** [comment]
@atgeirr: please close this PR if it has become obsolete.

**Pull request closed without merging**
