### PR TITLE
ebos: also install the headers of the applications subdirectory

### PR DESCRIPTION
**Pull request by andlaus**
this should make flow_ebos work for system-installed eWoms modules.

@akva2: can you test whether this works and if yes press the Green Button?

### CODE REVIEW

**Comment by akva2** [comment]
it would work but i don't think prefix/include/applications is very nice. i understand it has consequences but i really think prefix/include/ewoms/applications is more appropriate.

**Comment by andlaus** [comment]
ok, do you think `applications` should be removed? (i.e. the headers would directly go to `ebos`)

**Comment by akva2** [comment]
probably even better. my main concern is polluting prefix/include, though conflicts are unlikely it's still good to qualify the headers.

**Comment by andlaus** [comment]
ok, I've removed the "applications" directory. Note that now a (pretty trivial) change is needed for flow_ebos, too.

@akva2: if you're happy with this, please press green.

**Comment by andlaus** [comment]
> @akva2: if you're happy with this, please press green.

(in that case don't forget to also merge OPM/opm-simulators#908.)

**Comment by akva2** [comment]
i'm happy. i guess there is no point waiting for travis.

**Pull request merged**
