### PR TITLE
changed: sync with renaming to opm-common

### PR DESCRIPTION
**Pull request by akva2**
*Do not merge* before renaming with friends has happened.

### CODE REVIEW

**Comment by andlaus** [comment]
whoever merges OPM/opm-common#35, please merge this one too!

**Comment by andlaus** [comment]
`dune.module` and `configure` also need to be changed. also, I suppose it would be a good idea to add `opm-common` to the prereqs because in the future there is c++ code to be added to it. do you want to do this yourself, or do you prefer if I do it?

**Comment by akva2** [comment]
i welcome all help.

**Comment by atgeirr** [comment]
> I suppose it would be a good idea to add opm-common to the prereqs because in the future there is c++ code to be added to it

It should be done, but in the spirit of taking small steps and making sure they are successful, should we not wait until the dust settles on this change first?

**Comment by akva2** [comment]
yes, step by step.

who use these damn configure scripts anyways? this is cmake, not autotools. learn, adapt...

**Pull request merged**
