### PR TITLE
[bugfix][MatrixBlock] fix fallout from SparseMatrixAdapter merge for DUNE 2.4.1.

### PR DESCRIPTION
**Pull request by dr-robertk**
This fixes compilation issues mentioned in opm-simulators#1635.

### CODE REVIEW

**Comment by dr-robertk** [comment]
@GitPaean: Could you check if that fixes your problem. If  yes, plz push green.

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Yes. It fixed the compilation error mentioned in https://github.com/OPM/opm-simulators/issues/1635 . Thanks. 

I will not be able to wait the jenkins to finish. So someone else will press green tomorrow.

**Comment by dr-robertk** [comment]
I guess @atgeirr can do this first thing in the morning.

**Comment by dr-robertk** [comment]
I also checked with DUNE 2.5 and everything seems to compile there.

**Pull request merged**
