### PR TITLE
Fix coding style

### PR DESCRIPTION
**Pull request by andlaus**
This PR fixes multiple coding style issues that have accumulated in the code base with the purpose to make it more consistent. I've refrained from renaming anything which is used by downstream modules and thus intent self-merge it early next week.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Consistent style is good, but I think it is a bit of a time-waster to do it manually. Did you use clang-format or another automatic solution to do these changes? If so, it would be good to see the setup used.

**Comment by andlaus** [comment]
I did it manually, as I can't see how clang-format can be used for this. (I'm quite curious about the script which you promised!)

**Comment by andlaus** [comment]
(well, I should add that I used emacs' regex query-replace functextensively for this. this is far from automatable, though.)

**Comment by andlaus** [comment]
oops, wrong button.

**Comment by dr-robertk** [comment]
@andlaus, @atgeirr: Nice coding style is nice but a lot of "white space changes" are actually really terrible for those developing new features such as the OPM adjoint  branches by @hnil. 
A lot of conflicts will arise making it very difficult to maintain such branches. So from my side a clear "thumbs down"

**Comment by andlaus** [comment]
everybody who wants their branches rebased (and the conflicts resolved) by me after this PR is merged, please raise their hands and point to them. the only condition is that these branches must not conflict with master as of today.

**Comment by atgeirr** [comment]
> everybody who wants their branches rebased (and the conflicts resolved) by me after this PR is merged, please raise their hands and point to them. the only condition is that these branches must not conflict with master as of today.

Well, I would accept your offer, but cannot take you up on it until I have got the branches in question up to date again, so it must wait a little at least.

**Comment by andlaus** [comment]
no worries: if your branch HEAD has a4e383fc4b3c260db27fad013ef3641cf2fa1afd in its history, I vow to bring it to include ee9224f722c0710523880d683a040e80c536714d if you wish. This promise stands as long as I'm around.

**Comment by andlaus** [comment]
Okay, I'll merge this now: There should not be any difficult to resolve conflicts and my offer for the "porting service" still stands.

In the future, we should have a consistent policy of such changes: As far as I can see, the options are

1) allow the code base to become inconsistent
2) nit-pick a lot before merging PRs
3) be relatively lenient before merging PRs but do an occasional cleanup PR

So far I tended towards option (3), but if the project wide consensus is for one of the others, I'll budge as long as all other maintainers do the same.

**Pull request merged**
