### PR TITLE
Add opm-simulators to jenkins downstream list

### PR DESCRIPTION
**Pull request by akva2**
ignore the noise..

### CODE REVIEW

**Comment by akva2** [comment]
jenkins run polymer please

**Comment by akva2** [comment]
jenkins run polymer please

**Comment by akva2** [comment]
jenkins run polymer please

**Comment by akva2** [comment]
jenkins run polymer please

**Comment by akva2** [comment]
jenkins run polymer please

**Comment by akva2** [comment]
@andlaus found a real issue which is fixed in this pr.

**Comment by andlaus** [comment]
So the PR should be merged?

**Comment by akva2** [comment]
yes

**Comment by andlaus** [comment]
k. thanks!

**Pull request merged**
