### PR TITLE
fixed: restore build of ebos after opm-parser changes

### PR DESCRIPTION
**Pull request by akva2**
the WellConstPtr typedef is gone

### CODE REVIEW

**Comment by akva2** [comment]
@joakim-hove i think that was the change right (ditched the shared ptr and the typedef in the process ?)

**Comment by akva2** [comment]
jenkins build this please

**Comment by jokva** [comment]
Seems likely, yes.

**Comment by andlaus** [comment]
thanks

**Comment by andlaus** [comment]
one thing I'm wondering about: isn't there _a lot_ of potential with `struct Wells` from opm-core? (that one is located in `opm/core/wells.h`.)

**Comment by jokva** [comment]
There is.

**Pull request merged**
