### PR TITLE
fixed: need to deref these variables for newer cmake

### PR DESCRIPTION
**Pull request by akva2**
conditions always evaluated to true otherwise.

hopefully compatible with cmake 2.8 as well. jenkins will tell.

### CODE REVIEW

**Comment by akva2** [comment]
sigh. or not. jenkins is running cmake 3.0.2. i'll have to test on a vm then.

**Comment by andlaus** [comment]
no objections from my side, please merge this yourself when you think it is ready.

> sigh. or not. jenkins is running cmake 3.0.2. i'll have to test on a vm then.

maybe quotes around the condition fix it?

**Comment by akva2** [comment]
nope. it will then evaluate as a 'non-empty string' - always true.

**Comment by andlaus** [comment]
*darn* cmake is so convenient!

**Comment by akva2** [comment]
sorry for delay but building the whole chain in a 2-core VM takes some time. it works fine with cmake 2.8. let's check 3.0 just to be sure

**Comment by akva2** [comment]
jenkins build this please

**Comment by andlaus** [comment]
hm. this PR now conflicts with the legacy ALUGrid elimination patch which I pushed a few minutes ago. the conflicts should be quite easy to fix, though.

**Comment by akva2** [comment]
no worries.

**Comment by akva2** [comment]
rebased. merging.

**Pull request merged**
