### PR TITLE
fix build of ebos

### PR DESCRIPTION
**Pull request by akva2**
follow-up for pr #193

### CODE REVIEW

**Comment by akva2** [comment]
hold on this please.

**Comment by andlaus** [comment]
thanks for moping up after me. please merge yourself once you deem it to be ready.

**Comment by akva2** [comment]
i know you said to merge but i had to change strategy completely so double-checking.

**Comment by andlaus** [comment]
> i know you said to merge but i had to change strategy completely so double-checking.

take your time. as long as Jenkins is happy even without this, we're not in a hurry.

**Comment by akva2** [comment]
it's working fine with installation based builds, package based builds for libecl and dc. i have tested it all.

**Comment by akva2** [comment]
by double checking i meant if its fine to merge in the new form.

**Comment by akva2** [comment]
no response is a positive response ;)

**Pull request merged**
