### PR TITLE
simplify jenkins build scripts a little

### PR DESCRIPTION
**Pull request by akva2**
changes done related to downstream triggers made
it easier to build upstreams as well

depends on https://github.com/OPM/opm-common/pull/111

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=111 please

**Comment by akva2** [comment]
@andlaus ready for review.

**Comment by andlaus** [comment]
ready for merge :)

**Comment by akva2** [comment]
I thought i made the upstream dependency quite clear..

-------- Opprinnelig melding --------
Fra: Andreas Lauser <notifications@github.com>
Dato: 30.04.2016 11:02 (GMT+01:00)
Til: OPM/ewoms <ewoms@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>, Author <author@noreply.github.com>
Emne: Re: [OPM/ewoms] simplify jenkins build scripts a little (#56)


Merged #56<https://github.com/OPM/ewoms/pull/56>.

**Comment by andlaus** [comment]
seems like attention span is too low :/. Anyway, this should only affect the jenkins server? (I don't mind too much if it is broken until the upstream dependency is merged.)

**Comment by akva2** [comment]
Yes just jenkins. No sense in reverting anything.

-------- Opprinnelig melding --------
Fra: Andreas Lauser <notifications@github.com>
Dato: 30.04.2016 11:27 (GMT+01:00)
Til: OPM/ewoms <ewoms@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>, Author <author@noreply.github.com>
Emne: Re: [OPM/ewoms] simplify jenkins build scripts a little (#56)


seems like attention span is too low :/. Anyway, this should only affect the jenkins server? (I don't mind too much if it is broken until the upstream dependency is merged.)

**Pull request merged**
