### PR TITLE
Don't merge this 

### PR DESCRIPTION
**Pull request by totto82**
trivial change to generate new data

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
@akva2 Why does update_data create an issue not a PR?

**Comment by totto82** [comment]
@andlaus manually fixed this.

**Comment by akva2** [comment]
hi, it creates an issue cause that's the api provided. you open an issue, then you can convert this to a pull request by attaching branch information. since the branch was never opened due to other things, you are stuck with just the issue.

**Pull request closed without merging**
