### PR TITLE
EclSimulator: make compile with dune-alugrid

### PR DESCRIPTION
**Pull request by dr-robertk**
This patch makes the ebos simulator compile with ALUGrid (and by that assure that the code still follows the DUNE grid interface). 
For that reasons the identification to the Cartesian cell id has been moved to the grid manager. 
Some minor other fixes have been made to make the code compile. 
Also, I added the FindZOLTAN.cmake check but for some reasons it is not working correctly yet. 

The switch between CpGrid and ALUGrid needs to be put into the ewoms way by @andlaus.

### CODE REVIEW

**Comment by andlaus** [comment]
that's good stuff, thanks. The only issue minor I've found is that the zoltan cmake module and the corresponding change to `FindAlugrid.cmake` should be split out to a separate patch and added to opm-core as well. Having said this, I have no reservation to merge this PR this as-is and do the opm-core build system changes for you (whatever if you prefer)...

**Comment by dr-robertk** [comment]
I'll do the split. Why should one add this patch to the core?

**Comment by dr-robertk** [comment]
I merged the Zoltan Patch into the other one.  Was that it?

**Comment by dr-robertk** [comment]
I found a problem with the getIJK method. I needed to fix this before this is merged.

**Comment by andlaus** [comment]
> Why should one add this patch to the core? 

that's basically an ideosyncrasy of the build system: since everything needs to be copied to every module, it is easier to have a "central" module which is used for the syncronization. this central module happens to be opm-core.

> I found a problem with the getIJK method. I needed to fix this before this is merged.

ok, no problem. Just state when I should push the Big Green Guy.

**Comment by andlaus** [comment]
> I merged the Zoltan Patch into the other one. Was that it?

in principle, yes. (If you mean to include all other changes to the `cmake` directory in this patch, too.) But it seems like something went wrong, as to me it seems like the first patch of this PR still contains build system and non-buildsystem changes...

**Comment by dr-robertk** [comment]
I fixed the getIJK issue. ALUGrid does not run yet, but CpGrid still runs ;-)

**Comment by dr-robertk** [comment]
Now it also runs with ALUGrid.

**Comment by andlaus** [comment]
cool. in it goes, thanks.

**Pull request merged**
