### PR TITLE
each phase needs to be above certain value to be treated to be present

### PR DESCRIPTION
**Pull request by GitPaean**
it helps to recover some RESTART running based on single precision format.

Because saturation values are used to determine saturated/unsaturated region distribution, with this patch, we are more likely to get more continuous region distribution, numerically, more continuous primary variable distribution. 

Physically, it does not matter, while numerically, the linear system is easier to solve.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I added the re-scaling of the saturations to make sure the sum  is 1.0.  To avoid adding too much length to the original function, I put this part to be a separate function.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
As the requested changes were made I think this should be merged. Also, it only affects (and improves) restarting, so there is little risk. @andlaus?

**Comment by andlaus** [comment]
agreed. merging.

**Pull request merged**
