### PR TITLE
black oil newton method: allow the compiler to see at compile time if  a given extension is enabled

### PR DESCRIPTION
**Pull request by andlaus**
i.e., we now check for `enable$BLACKOIL_EXTENSION` compile time variables. this should allow the compiler to produce slightly better optimized machine code if the respective extension is disabled.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
okay, there was a stupid mistake here: if you want the minimal temperature to be 100 K, you have to use `std::max(100, T)`, not `std::min(100, T)`...

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
with the stupidity fixed, it actually works. Wow?

@totto82: if you're okay with this, I'd appreciate if you pressed Green.

**Comment by totto82** [comment]
Does this fix the convergence issue for the energy model? 

Anyway, looks good, and Jenkins is happy.

**Comment by andlaus** [comment]
thanks for merging!

> Does this fix the convergence issue for the energy model?

not that I know of. While doing this, I just stumbled over the fact that all other blackoil extensions had crash barriers around their update paths but not the energy extension. I thought that it was a good idea to fix this while at it...

**Pull request merged**
