### PR TITLE
change the order of OPM_UNUSED and variable name

### LINKED ISSUE #128: OPM_UNUSED not working as expected
```
/home/mblatt/src/dune/opm/ewoms/ebos/eclproblem.hh:778:45: warning: unused parameter ‘context’ [-Wunused-parameter]
                   const Context& OPM_UNUSED context,
```
BTW `HAS_ATTRIBUTE_UNUSED` is defined to 1 according to config.h

### PR DESCRIPTION
**Pull request by andlaus**
it seems like some compilers (GCC 4.9.2?) are picky about this and
require

```c++
TypeName VariableName __attribute__ ((__unused__))
```

This should fix #128...

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by blattms** [comment]
Thanks. This did the trick.

**Comment by andlaus** [comment]
> Thanks. This did the trick.

you're welcome :). IMO this has been a quite weird issue because you only saw one warning, right? (there should be plenty of other unused arguments.)

**Comment by blattms** [comment]
I saw lots of them. But posting suffices as a show case.

**Comment by andlaus** [comment]
ah, ok.

**Pull request merged**
